# Generated by Django 5.1.15 on 2026-06-11 15:02

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('jobs', '0021_pending_subscription_price_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('accessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credential_access_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-access_time'],
            },
        ),
        migrations.CreateModel(
            name='CredentialDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.CharField(blank=True, max_length=300)),
                ('scope_notes', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('staff_contacted', 'Staff Contacted'), ('confirmed', 'Confirmed'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('staff_notes', models.TextField(blank=True)),
                ('re_onboarding_fee_disclosed', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deletion_requests', to='jobs.customer')),
                ('staff_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('device_type', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_devices', to='jobs.job')),
            ],
            options={
                'ordering': ['system', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('credential_type', models.CharField(choices=[('password', 'Password'), ('api_key', 'API Key'), ('pin', 'PIN'), ('other', 'Other')], max_length=20)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('value', encrypted_model_fields.fields.EncryptedCharField()),
                ('notes', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='client_credentials.device')),
            ],
        ),
        migrations.CreateModel(
            name='InstalledSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(choices=[('lighting', 'Lighting Control'), ('hvac', 'HVAC / Climate Control'), ('networking', 'Networking / WiFi Infrastructure'), ('video', 'Video Systems'), ('shades', 'Motorized Shades / Blinds'), ('access', 'Access Control'), ('presence', 'Presence Detection'), ('control_interface', 'Control Interface'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installed_systems', to='jobs.customer')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_systems', to='jobs.job')),
            ],
            options={
                'ordering': ['customer', 'system_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='client_credentials.installedsystem'),
        ),
        migrations.CreateModel(
            name='SystemCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('portal_url', models.CharField(blank=True, max_length=500)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('password', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='client_credentials.installedsystem')),
            ],
        ),
    ]
