# Generated by Django 5.1.15 on 2026-06-12 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_credentials', '0001_initial'),
        ('jobs', '0025_add_property_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installedsystem',
            options={'ordering': ['property', 'system_type', 'name']},
        ),
        migrations.RemoveField(
            model_name='installedsystem',
            name='customer',
        ),
        migrations.AddField(
            model_name='installedsystem',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='installed_systems', to='jobs.property'),
        ),
    ]
