# Generated by Django 5.1.15 on 2026-05-12 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=200)),
                (
                    "intro_md",
                    models.TextField(
                        blank=True,
                        help_text="Optional Markdown intro shown above the items in this step.",
                    ),
                ),
            ],
            options={
                "ordering": ["template", "order"],
            },
        ),
        migrations.RemoveField(
            model_name="backendinstall",
            name="progress",
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "body_md",
                    models.TextField(
                        help_text="Markdown body of the checklist item: instruction text, code blocks, links."
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="jobs.checkliststep",
                    ),
                ),
            ],
            options={
                "ordering": ["step", "order"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60)),
                ("version", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                (
                    "changelog",
                    models.TextField(
                        blank=True,
                        help_text="What changed in this version vs. the previous one.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["slug", "-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("slug", "version"), name="unique_template_version"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="checkliststep",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="jobs.checklisttemplate",
            ),
        ),
        migrations.AddField(
            model_name="backendinstall",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Snapshot reference: this BackendInstall renders against this exact template version, even if a newer version is published later.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="backend_installs",
                to="jobs.checklisttemplate",
            ),
        ),
        migrations.CreateModel(
            name="BackendInstallItemState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checked", models.BooleanField(default=False)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Per-item installer notes (e.g. 'used 16GB drive — none in stock').",
                    ),
                ),
                (
                    "backend_install",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_states",
                        to="jobs.backendinstall",
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="jobs.checklistitem",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("backend_install", "item"),
                        name="unique_backend_item_state",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="checklistitem",
            constraint=models.UniqueConstraint(
                fields=("step", "order"), name="unique_item_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="checkliststep",
            constraint=models.UniqueConstraint(
                fields=("template", "order"), name="unique_step_order"
            ),
        ),
    ]
