# Generated by Django 5.1.15 on 2026-05-12 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_checklist_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistitem",
            name="capture_key",
            field=models.SlugField(
                blank=True,
                help_text="Slug key for capture items (e.g. 'hostname', 'nuc_static_ip'). Per-install values are stored in BackendInstallCapture keyed by this slug.",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="checklistitem",
            name="capture_label",
            field=models.CharField(
                blank=True,
                help_text="Label shown next to the capture input (e.g. 'HAOS Hostname').",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="checklistitem",
            name="capture_placeholder",
            field=models.CharField(
                blank=True,
                help_text="Placeholder text for the capture input (e.g. 'e.g. HASmitr').",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="checklistitem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("check", "Checkbox item"),
                    ("content", "Content block"),
                    ("capture", "Capture input"),
                ],
                default="check",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="checklistitem",
            name="body_md",
            field=models.TextField(
                blank=True,
                help_text="Markdown/HTML body. For check items: the instruction. For content items: the rendered block (prose, code, callout, nav path). For capture items: optional helper text shown next to the input.",
            ),
        ),
        migrations.CreateModel(
            name="BackendInstallCapture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=60)),
                ("value", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "backend_install",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captures",
                        to="jobs.backendinstall",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("backend_install", "key"),
                        name="unique_backend_capture_key",
                    )
                ],
            },
        ),
    ]
