# Generated by Django 5.1.15 on 2026-05-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_port_install_html"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checklistitem",
            options={"ordering": ["step", "order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="checkliststep",
            options={"ordering": ["template", "order", "id"]},
        ),
        migrations.RemoveConstraint(
            model_name="checklistitem",
            name="unique_item_order",
        ),
        migrations.RemoveConstraint(
            model_name="checkliststep",
            name="unique_step_order",
        ),
        migrations.AlterField(
            model_name="checklistitem",
            name="order",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Sort order within the step. To insert a new item between existing ones, use a fractional value (e.g. 2.5 to land between 2 and 3); on save the admin renumbers every item to clean sequential integers.",
                max_digits=6,
            ),
        ),
        migrations.AlterField(
            model_name="checkliststep",
            name="order",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Sort order within the template. To insert a new step between existing ones, use a fractional value (e.g. 2.5 to land between 2 and 3); on save the admin renumbers every step to clean sequential integers.",
                max_digits=6,
            ),
        ),
    ]
