# Generated by Django 5.2.14 on 2026-05-13 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_orderable_items"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("nuc", "NUC / Server"),
                            ("switch", "Network switch"),
                            ("ap", "Access point"),
                            ("sensor", "Sensor"),
                            ("camera", "Camera"),
                            ("lock", "Smart lock"),
                            ("thermostat", "Thermostat"),
                            ("hub", "Hub / bridge"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(max_length=200)),
                ("supplier", models.CharField(blank=True, max_length=200)),
                ("supplier_sku", models.CharField(blank=True, max_length=100)),
                ("purchase_url", models.URLField(blank=True)),
                (
                    "default_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["device_type", "model_name"],
            },
        ),
        migrations.CreateModel(
            name="PreInstallChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_install_checklist",
                        to="jobs.job",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Snapshot reference: this checklist renders against this exact template version, even if a newer version is published later.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pre_install_checklists",
                        to="jobs.checklisttemplate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PreInstallCapture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=60)),
                ("value", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pre_install_checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captures",
                        to="jobs.preinstallchecklist",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pre_install_checklist", "key"),
                        name="unique_pre_install_capture_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PreInstallItemState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checked", models.BooleanField(default=False)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Per-item installer notes."),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="jobs.checklistitem",
                    ),
                ),
                (
                    "pre_install_checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_states",
                        to="jobs.preinstallchecklist",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pre_install_checklist", "item"),
                        name="unique_pre_install_item_state",
                    )
                ],
            },
        ),
    ]
