# Generated by Django 5.2.14 on 2026-05-13 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_pre_install_checklist_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "base_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Base sale price for this package.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InternalPrep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_username", models.CharField(blank=True, max_length=100)),
                ("github_created", models.BooleanField(default=False)),
                ("picklist_picked", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_prep",
                        to="jobs.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PackageDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="package_lines",
                        to="jobs.catalogdevice",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="jobs.package",
                    ),
                ),
            ],
            options={
                "ordering": ["device__device_type", "device__model_name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("living_room", "Living room"),
                            ("kitchen", "Kitchen"),
                            ("dining_room", "Dining room"),
                            ("bedroom", "Bedroom"),
                            ("bathroom", "Bathroom"),
                            ("office", "Office"),
                            ("garage", "Garage"),
                            ("basement", "Basement"),
                            ("laundry", "Laundry room"),
                            ("hallway", "Hallway"),
                            ("entryway", "Entryway"),
                            ("outdoor", "Backyard / outdoor"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "custom_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional label to distinguish this room from others of the same type (e.g. 'Master', 'Kids', 'Grandma's').",
                        max_length=100,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="RoomDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Customer confirmed this device goes in this room.",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="room_devices",
                        to="jobs.catalogdevice",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="jobs.room",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SaleLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Snapshot of the device cost at time of sale.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                ("confirmed_in_stock", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_lines",
                        to="jobs.catalogdevice",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_lines",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
