# Generated by Django 5.1.15 on 2026-05-14 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0017_fix_component_search_strings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="display_invoice_number",
            field=models.CharField(
                blank=True,
                help_text="System-generated customer-facing invoice code (YYMMDD + service-plan-tier + rooms + adhoc + seq). Set when the pre-install walkthrough is finalized.",
                max_length=30,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="package",
            field=models.ForeignKey(
                blank=True,
                help_text="Install package selected at sale time.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="jobs.package",
            ),
        ),
    ]
