# Generated by Django 5.1.15 on 2026-05-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_alter_job_display_invoice_number_alter_job_package'),
        ('jobs', '0017_fix_component_search_strings'),
    ]

    operations = [
    ]
