# Generated by Django 5.1.15 on 2026-05-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_pairing_sheet_structured'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID (cus_...). Set on first Stripe interaction. Never set manually.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='final_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='plan_tier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stripe_deposit_invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stripe_deposit_invoice_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stripe_final_invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stripe_final_invoice_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stripe_quote_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('sold', 'Sold'), ('deposit_received', 'Deposit Received'), ('pre_install', 'Pre-install'), ('backend', 'Backend prep'), ('pairing', 'Pairing'), ('automation', 'Automation config'), ('onsite', 'On-site install'), ('walkthrough', 'Walkthrough'), ('final_paid', 'Final Paid'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='sold', max_length=20),
        ),
    ]
