# Generated by Django 5.1.15 on 2026-06-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_customer_stripe_customer_id_job_deposit_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pending_subscription_price_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
