# Generated by Django 5.1.15 on 2026-06-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_pending_subscription_price_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceSubscription',
        ),
    ]
