# Generated by Django 5.1.15 on 2026-06-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_service_tier_unification'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='billing_interval',
            field=models.CharField(blank=True, choices=[('none', 'N/A'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='display_invoice_number',
            field=models.CharField(blank=True, help_text='System-generated customer-facing invoice code (YYMMDD + rooms + adhoc + seq, 13 chars). Set when the pre-install walkthrough is finalized.', max_length=30, null=True, unique=True),
        ),
    ]
