# Generated by Django 5.1.15 on 2026-06-12 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_add_billing_interval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='job',
            name='billing_interval',
        ),
        migrations.RemoveField(
            model_name='job',
            name='pending_subscription_price_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='service_plan_tier',
        ),
        migrations.RemoveField(
            model_name='job',
            name='stripe_subscription_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='subscription_status',
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Primary Residence', max_length=200)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=40)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_status', models.CharField(blank=True, max_length=50, null=True)),
                ('service_plan_tier', models.CharField(blank=True, choices=[('none', 'No Service Plan'), ('tier1', 'Basic'), ('tier2', 'Standard'), ('tier3', 'Premium')], default='none', max_length=10)),
                ('billing_interval', models.CharField(blank=True, choices=[('none', 'N/A'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='none', max_length=10)),
                ('pending_subscription_price_id', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='jobs.customer')),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['customer', 'name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='jobs.property'),
        ),
    ]
